server:
    port: 8004

spring:
    datasource:
        url: "jdbc:postgresql://localhost/HistoricalServiceDB"
        username: "postgres"
        password: "AIClab!"
    jpa:
        generate-ddl: true
    mvc:
        pathmatch:
            matching-strategy: "ant-path-matcher"

moexservice:
    url: "http://localhost:8005/currency/getCurrency"
    pinginterval: 60000
    pairs:
        - USD000UTSTOM
        - EUR_RUB__TOM
        - CNYRUB_TOM

logging:
    level:
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: "DEBUG"








