#
# Build stage
#
FROM maven:3-openjdk-17-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml package spring-boot:repackage

#
# Package stage
#
FROM bellsoft/liberica-openjre-alpine:17
COPY --from=build /home/app/target/MOEXService-0.0.1-SNAPSHOT.jar /usr/local/lib/MOEXService.jar
EXPOSE 8005
ENTRYPOINT ["java","-jar","/usr/local/lib/MOEXService.jar"]